(function () {
  window.GinRanges = {
    cards: {
      id: "cards",
      title: "Cards",
      lede:
        "Greeting cards from the brands on our Histon shelves. Choose a range, then call the shop and we will put a piece aside for collection or local delivery.",
    },
    gifts: {
      id: "gifts",
      title: "Gifts",
      lede:
        "Gifts from the brands we stock beside the flowers. Choose a range, then call the shop and we will put a piece aside for collection or local delivery.",
    },
    chocolate: {
      id: "chocolate",
      title: "Chocolate",
      lede:
        "Handmade chocolate from The Cambridge Confectionery Company, for collection from Histon or local delivery.",
    },
    brands: [
      {
        id: "ohh-deer",
        name: "Ohh Deer",
        note: "Greeting cards",
        blurb: "Illustrated cards and stationery from independent artists.",
        groups: ["cards"],
        image: "images/ranges/ohh-deer.jpg",
        imageAlt: "Ohh Deer greeting card with a black and white cat",
      },
      {
        id: "the-art-file",
        name: "The Art File",
        note: "Greeting cards",
        blurb: "Design-led greeting cards, wrap and stationery.",
        groups: ["cards"],
        image: "images/ranges/the-art-file.jpg",
        imageAlt: "The Art File birthday card with cats around a cake",
      },
      {
        id: "caroline-gardner",
        name: "Caroline Gardner",
        note: "Cards and stationery",
        blurb: "Patterned cards, stationery and small gifts.",
        groups: ["cards"],
        image: "images/ranges/caroline-gardner.jpg",
        imageAlt: "Caroline Gardner floral card reading you are wonderful",
      },
      {
        id: "rachel-ellen",
        name: "Rachel Ellen",
        note: "Greeting cards",
        blurb: "Bright, hand-painted cards and gifts, especially for children.",
        groups: ["cards"],
        image: "images/ranges/rachel-ellen.jpg",
        imageAlt: "Rachel Ellen mermaid birthday card for age three",
      },
      {
        id: "paper-salad",
        name: "Paper Salad",
        note: "Cards",
        blurb: "Bold, hand-painted cards with bright colour and texture.",
        groups: ["cards"],
        image: "images/ranges/paper-salad.png",
        imageAlt: "Paper Salad card reading sending you the biggest hugs and all the love",
      },
      {
        id: "museums-galleries",
        name: "Museums & Galleries",
        note: "Art-inspired cards and gifts",
        blurb: "Cards and gifts drawn from museum and gallery art.",
        groups: ["cards", "gifts"],
        image: "images/ranges/museums-galleries.jpg",
        imageAlt: "Museums and Galleries art greeting cards laid out together",
      },
      {
        id: "jellycat",
        name: "Jellycat",
        note: "Soft toys",
        blurb: "Soft toys with gentle humour and unusual colours.",
        groups: ["gifts"],
        image: "images/ranges/jellycat.jpg",
        imageAlt: "Jellycat beige bunny holding a small cake",
      },
      {
        id: "talking-tables",
        name: "Talking Tables",
        note: "Party and tableware",
        blurb: "Party tableware and decorations for gatherings.",
        groups: ["gifts"],
        image: "images/ranges/talking-tables.jpg",
        imageAlt: "Talking Tables colourful happy birthday candle on a cake",
      },
      {
        id: "cambridge-confectionery",
        name: "The Cambridge Confectionery Company",
        note: "Chocolate",
        blurb: "Handmade chocolate, fudge and sweets from Cambridgeshire.",
        groups: ["chocolate"],
        image: "images/ranges/cambridge-confectionery.png",
        imageAlt: "Cambridge Confectionery Company rocky road chocolate bars",
      },
      {
        id: "st-eval",
        name: "St Eval Candles",
        note: "Candles",
        blurb: "Scented candles made on the north Cornwall coast.",
        groups: ["gifts"],
        image: "images/ranges/st-eval.jpg",
        imageAlt: "St Eval bay and rosemary scented tin candle",
      },
      {
        id: "olor",
        name: "Olor Home Fragrance",
        note: "Home fragrance",
        blurb: "Home fragrance, from reed diffusers to scented candles.",
        groups: ["gifts"],
        image: "images/ranges/olor.jpg",
        imageAlt: "Olor bay tree and blackberry reed diffuser and box",
      },
      {
        id: "dcuk",
        name: "Dcuk",
        note: "Gifts",
        blurb: "Hand-painted wooden ducks and animal characters.",
        groups: ["gifts"],
        image: "images/ranges/dcuk.jpg",
        imageAlt: "Dcuk wooden hedgehogs wearing mushroom caps",
      },
      {
        id: "scottish-fine-soaps",
        name: "Scottish Fine Soaps",
        note: "Soaps",
        blurb: "Soaps, washes and lotions inspired by Scotland.",
        groups: ["gifts"],
        image: "images/ranges/scottish-fine-soaps.jpg",
        imageAlt: "Scottish Fine Soaps amber and oakmoss hand wash",
      },
      {
        id: "willsow",
        name: "Willsow",
        note: "Gifts",
        blurb: "Plantable books and paper grown with wildflower seeds.",
        groups: ["gifts"],
        image: "images/ranges/willsow.jpg",
        imageAlt: "Willsow plantable Shaun the Sheep children's book",
      },
    ],
  };
})();
