(function (root, factory) {
  var products = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = { PAPER_SALAD: products };
  }
  if (root && root.window === root) {
    root.GinPaperSalad = products;
  }
})(typeof window !== "undefined" ? window : this, function () {
  // Spring cards (Valentine's, Mother's and Father's Day) stay hidden until this date.
  var SPRING_ON_SALE_FROM = "2027-01-04";

  var everyday = [
    {
      id: "ps-ja21249",
      sku: "JA21249",
      name: "Birthday Queen",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Open birthday",
      styles: [],
      blurb: "Blank inside. From the Jamboree range.",
      image: "images/cards/ps-ja21249.jpg",
      imageAlt: "Birthday Queen greeting card by Paper Salad",
    },
    {
      id: "ps-ja21254",
      sku: "JA21254",
      name: "Let's Party Disco Ball",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Open birthday",
      styles: [],
      blurb: "The caption reads Let's Party, it's your birthday. Blank inside. From the Jamboree range.",
      image: "images/cards/ps-ja21254.jpg",
      imageAlt: "Let's Party Disco Ball birthday card by Paper Salad",
    },
    {
      id: "ps-gd2435",
      sku: "GD2435",
      name: "Happy Birthday Lovely Niece",
      price: 3.25,
      pricePence: 325,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Birthday for Niece",
      styles: [],
      blurb: "A birthday card for a niece. Blank inside. From the Gold Dust range.",
      image: "images/cards/ps-gd2435.jpg",
      imageAlt: "Happy Birthday Lovely Niece card by Paper Salad",
    },
    {
      id: "ps-gd2436",
      sku: "GD2436",
      name: "To a Special Wife on Your Birthday",
      price: 3.25,
      pricePence: 325,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Birthday for Wife",
      styles: [],
      blurb: "A birthday card for a wife. Blank inside. From the Gold Dust range.",
      image: "images/cards/ps-gd2436.jpg",
      imageAlt: "To a Special Wife on Your Birthday card by Paper Salad",
    },
    {
      id: "ps-am2411",
      sku: "AM2411",
      name: "Just Married",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Wedding",
      styles: [],
      blurb: "Blank inside. From the Alchemy range.",
      image: "images/cards/ps-am2411.jpg",
      imageAlt: "Just Married greeting card by Paper Salad",
    },
    {
      id: "ps-am2422",
      sku: "AM2422",
      name: "Wedding Day",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Wedding",
      styles: [],
      blurb: "Blank inside. From the Alchemy range.",
      image: "images/cards/ps-am2422.jpg",
      imageAlt: "Wedding Day greeting card by Paper Salad",
    },
    {
      id: "ps-gd1767",
      sku: "GD1767",
      name: "On Your Wedding Day",
      price: 3.25,
      pricePence: 325,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Wedding",
      styles: ["Floral"],
      blurb: "The caption reads On your Wedding Day. Blank inside. From the Gold Dust range.",
      image: "images/cards/ps-gd1767.jpg",
      imageAlt: "On Your Wedding Day card by Paper Salad",
    },
    {
      id: "ps-am2414",
      sku: "AM2414",
      name: "Happy Anniversary Heart",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Anniversary",
      styles: [],
      blurb: "Blank inside. From the Alchemy range.",
      image: "images/cards/ps-am2414.jpg",
      imageAlt: "Happy Anniversary Heart card by Paper Salad",
    },
    {
      id: "ps-px1904",
      sku: "PX1904",
      name: "You're Engaged",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Engagement",
      styles: [],
      blurb: "Blank inside. From the Pixie range.",
      image: "images/cards/ps-px1904.jpg",
      imageAlt: "You're Engaged greeting card by Paper Salad",
    },
    {
      id: "ps-vt2207",
      sku: "VT2207",
      name: "Baby Girl",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "New baby",
      styles: [],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2207.jpg",
      imageAlt: "Baby Girl greeting card by Paper Salad",
    },
    {
      id: "ps-vt2208",
      sku: "VT2208",
      name: "Baby Boy",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "New baby",
      styles: [],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2208.jpg",
      imageAlt: "Baby Boy greeting card by Paper Salad",
    },
    {
      id: "ps-vt2201",
      sku: "VT2201",
      name: "New Home",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "New home",
      styles: [],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2201.jpg",
      imageAlt: "New Home greeting card by Paper Salad",
    },
    {
      id: "ps-fl2307",
      sku: "FL2307",
      name: "Thank You",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Thank you",
      styles: ["Floral"],
      blurb: "Blank inside. From the Fleurescent range.",
      image: "images/cards/ps-fl2307.jpg",
      imageAlt: "Thank You greeting card by Paper Salad, with tulips",
    },
    {
      id: "ps-ma2312",
      sku: "MA2312",
      name: "Thank You",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Thank you",
      styles: ["Floral"],
      blurb: "Blank inside. From the Matisse range.",
      image: "images/cards/ps-ma2312.jpg",
      imageAlt: "Thank You greeting card by Paper Salad, from the Matisse range",
    },
    {
      id: "ps-vt2227",
      sku: "VT2227",
      name: "Thank You Floral",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Thank you",
      styles: ["Floral"],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2227.jpg",
      imageAlt: "Thank You Floral greeting card by Paper Salad",
    },
    {
      id: "ps-am2410",
      sku: "AM2410",
      name: "Yay!",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Well done",
      styles: [],
      blurb: "Blank inside. From the Alchemy range.",
      image: "images/cards/ps-am2410.jpg",
      imageAlt: "Yay! greeting card by Paper Salad",
    },
    {
      id: "ps-vt2212",
      sku: "VT2212",
      name: "Here for You",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Thinking of you",
      styles: ["Floral"],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2212.jpg",
      imageAlt: "Here for You greeting card by Paper Salad",
    },
    {
      id: "ps-vt2214",
      sku: "VT2214",
      name: "Get Well",
      price: 3,
      pricePence: 300,
      brand: "Paper Salad",
      group: "cards",
      product: "Greeting card",
      occasion: "Get well",
      styles: [],
      blurb: "Blank inside. From the Vista range.",
      image: "images/cards/ps-vt2214.jpg",
      imageAlt: "Get Well greeting card by Paper Salad",
    },
  ];

  var spring = [];

  var onSale = Date.now() >= new Date(SPRING_ON_SALE_FROM + "T00:00:00").getTime();
  return everyday.concat(onSale ? spring : []);
});
